import { cn } from '@/helpers/cn'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NavBar } from './components'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={cn('antialiased bg-slate-890 text-white', inter.className)}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
